(cl:defpackage piksi_rtk_msgs-srv
  (:use )
  (:export
   "SETTINGSREADREQ"
   "<SETTINGSREADREQ-REQUEST>"
   "SETTINGSREADREQ-REQUEST"
   "<SETTINGSREADREQ-RESPONSE>"
   "SETTINGSREADREQ-RESPONSE"
   "SETTINGSREADRESP"
   "<SETTINGSREADRESP-REQUEST>"
   "SETTINGSREADRESP-REQUEST"
   "<SETTINGSREADRESP-RESPONSE>"
   "SETTINGSREADRESP-RESPONSE"
   "SETTINGSWRITE"
   "<SETTINGSWRITE-REQUEST>"
   "SETTINGSWRITE-REQUEST"
   "<SETTINGSWRITE-RESPONSE>"
   "SETTINGSWRITE-RESPONSE"
  ))

