# General Settings.
sampling_frequency: 2.0         # [Hz]
kml_layout: "LineString"        # LineString or Placemark.
kml_altitude_mode: "absolute"   # relativeToGround, absolute, relativeToSeaFloor, clampToGround, clampToSeaFloor.
use_altitude_from_enu: False    # Place 'Point' at the altitude specified in 'enu_point' topic. Use kml_altitude_mode = relativeToGround.
extrude_point: True             # Connect the point to the ground with a line, only if use_altitude_from_enu is True.
use_heading: True               # If true, heading is added to 'Point' description.

# KML Placemark layout
placemarker_prefix_name: "WP"   # It will be prefixed to each incremental waypoint number.

# KML LineString layout
tessellate: 0                   # Breaks the line up into smaller chunks.
