(cl:in-package piksi_rtk_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TOW-VAL
          TOW
          NS_RESIDUAL-VAL
          NS_RESIDUAL
          WN-VAL
          WN
          N_OBS-VAL
          N_OBS
          P-VAL
          P
          L_I-VAL
          L_I
          L_F-VAL
          L_F
          D_I-VAL
          D_I
          D_F-VAL
          D_F
          CN0-VAL
          CN0
          LOCK-VAL
          LOCK
          FLAGS-VAL
          FLAGS
          SID_SAT-VAL
          SID_SAT
          SID_CODE-VAL
          SID_CODE
))