(cl:in-package piksi_rtk_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NUM_SAT-VAL
          NUM_SAT
          RTK_MODE_FIX-VAL
          RTK_MODE_FIX
          SAT-VAL
          SAT
          CN0-VAL
          CN0
          SYSTEM_ERROR-VAL
          SYSTEM_ERROR
          IO_ERROR-VAL
          IO_ERROR
          SWIFT_NAP_ERROR-VAL
          SWIFT_NAP_ERROR
          EXTERNAL_ANTENNA_PRESENT-VAL
          EXTERNAL_ANTENNA_PRESENT
          NUM_GPS_SAT-VAL
          NUM_GPS_SAT
          CN0_GPS-VAL
          CN0_GPS
          NUM_SBAS_SAT-VAL
          NUM_SBAS_SAT
          CN0_SBAS-VAL
          CN0_SBAS
          NUM_GLONASS_SAT-VAL
          NUM_GLONASS_SAT
          CN0_GLONASS-VAL
          CN0_GLONASS
          FIX_MODE-VAL
          FIX_MODE
))