// Generated by gencpp from file piksi_rtk_msgs/BaselineHeading.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_BASELINEHEADING_H
#define PIKSI_RTK_MSGS_MESSAGE_BASELINEHEADING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct BaselineHeading_
{
  typedef BaselineHeading_<ContainerAllocator> Type;

  BaselineHeading_()
    : header()
    , tow(0)
    , heading(0)
    , n_sats(0)
    , flags(0)  {
    }
  BaselineHeading_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tow(0)
    , heading(0)
    , n_sats(0)
    , flags(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _tow_type;
  _tow_type tow;

   typedef uint32_t _heading_type;
  _heading_type heading;

   typedef uint8_t _n_sats_type;
  _n_sats_type n_sats;

   typedef uint8_t _flags_type;
  _flags_type flags;





  typedef boost::shared_ptr< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> const> ConstPtr;

}; // struct BaselineHeading_

typedef ::piksi_rtk_msgs::BaselineHeading_<std::allocator<void> > BaselineHeading;

typedef boost::shared_ptr< ::piksi_rtk_msgs::BaselineHeading > BaselineHeadingPtr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::BaselineHeading const> BaselineHeadingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'piksi_rtk_msgs': ['/home/mensonli/FusionAD/src/utility/ethz_piksi_ros/piksi_rtk_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2898fbd48c60846b0ee32eacef99afae";
  }

  static const char* value(const ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2898fbd48c60846bULL;
  static const uint64_t static_value2 = 0x0ee32eacef99afaeULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/BaselineHeading";
  }

  static const char* value(const ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message reports the baseline heading pointing from the base station to the rover relative to True\n\
# North. The full GPS time is given by the preceding MSG GPS TIME with the matching time-of-week\n\
# (tow). It is intended that time-matched RTK mode is used when the base station is moving.\n\
\n\
Header header\n\
\n\
uint32 tow          # GPS Time of Week [ms].\n\
uint32 heading      # Heading [mdeg].\n\
uint8  n_sats       # Number of satellites used in solution\n\
uint8  flags        # Status flag.\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tow);
      stream.next(m.heading);
      stream.next(m.n_sats);
      stream.next(m.flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BaselineHeading_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_rtk_msgs::BaselineHeading_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tow: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tow);
    s << indent << "heading: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.heading);
    s << indent << "n_sats: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.n_sats);
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_BASELINEHEADING_H
