// Generated by gencpp from file piksi_rtk_msgs/GpsTimeMulti.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_GPSTIMEMULTI_H
#define PIKSI_RTK_MSGS_MESSAGE_GPSTIMEMULTI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct GpsTimeMulti_
{
  typedef GpsTimeMulti_<ContainerAllocator> Type;

  GpsTimeMulti_()
    : header()
    , wn(0)
    , tow(0)
    , ns_residual(0)
    , flags(0)  {
    }
  GpsTimeMulti_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , wn(0)
    , tow(0)
    , ns_residual(0)
    , flags(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _wn_type;
  _wn_type wn;

   typedef uint32_t _tow_type;
  _tow_type tow;

   typedef int32_t _ns_residual_type;
  _ns_residual_type ns_residual;

   typedef uint8_t _flags_type;
  _flags_type flags;





  typedef boost::shared_ptr< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> const> ConstPtr;

}; // struct GpsTimeMulti_

typedef ::piksi_rtk_msgs::GpsTimeMulti_<std::allocator<void> > GpsTimeMulti;

typedef boost::shared_ptr< ::piksi_rtk_msgs::GpsTimeMulti > GpsTimeMultiPtr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::GpsTimeMulti const> GpsTimeMultiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'piksi_rtk_msgs': ['/home/mensonli/FusionAD/src/utility/ethz_piksi_ros/piksi_rtk_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c23173761fc276afe3f4db2728518721";
  }

  static const char* value(const ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc23173761fc276afULL;
  static const uint64_t static_value2 = 0xe3f4db2728518721ULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/GpsTimeMulti";
  }

  static const char* value(const ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message reports the GPS time, representing the time since the GPS epoch began on midnight\n\
# January 6, 1980 UTC. GPS time counts the weeks and seconds of the week. The weeks begin at the\n\
# Saturday/Sunday transition. GPS week 0 began at the beginning of the GPS time scale.\n\
# Within each week number, the GPS time of the week is between between 0 and 604800 seconds\n\
# (=60*60*24*7). Note that GPS time does not accumulate leap seconds, and as of now, has a small offset\n\
# from UTC. In a message stream, this message precedes a set of other navigation messages referenced\n\
# to the same time (but lacking the ns field) and indicates a more precise time of these messages.\n\
\n\
Header header\n\
\n\
uint32 wn          # GPS week number [weeks].\n\
uint32 tow         # GPS time of week rounded to the nearest millisecond [ms].\n\
int32 ns_residual  # Nanosecond residual of millisecond-rounded TOW (ranges from -500000 to 500000) [ns].\n\
uint8 flags        # Status flags (reserved).\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.wn);
      stream.next(m.tow);
      stream.next(m.ns_residual);
      stream.next(m.flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsTimeMulti_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_rtk_msgs::GpsTimeMulti_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "wn: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.wn);
    s << indent << "tow: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tow);
    s << indent << "ns_residual: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ns_residual);
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_GPSTIMEMULTI_H
