// Generated by gencpp from file piksi_rtk_msgs/ImuRawMulti.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_IMURAWMULTI_H
#define PIKSI_RTK_MSGS_MESSAGE_IMURAWMULTI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct ImuRawMulti_
{
  typedef ImuRawMulti_<ContainerAllocator> Type;

  ImuRawMulti_()
    : header()
    , tow(0)
    , tow_f(0)
    , acc_x(0)
    , acc_y(0)
    , acc_z(0)
    , gyr_x(0)
    , gyr_y(0)
    , gyr_z(0)  {
    }
  ImuRawMulti_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tow(0)
    , tow_f(0)
    , acc_x(0)
    , acc_y(0)
    , acc_z(0)
    , gyr_x(0)
    , gyr_y(0)
    , gyr_z(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _tow_type;
  _tow_type tow;

   typedef uint8_t _tow_f_type;
  _tow_f_type tow_f;

   typedef int16_t _acc_x_type;
  _acc_x_type acc_x;

   typedef int16_t _acc_y_type;
  _acc_y_type acc_y;

   typedef int16_t _acc_z_type;
  _acc_z_type acc_z;

   typedef int16_t _gyr_x_type;
  _gyr_x_type gyr_x;

   typedef int16_t _gyr_y_type;
  _gyr_y_type gyr_y;

   typedef int16_t _gyr_z_type;
  _gyr_z_type gyr_z;





  typedef boost::shared_ptr< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> const> ConstPtr;

}; // struct ImuRawMulti_

typedef ::piksi_rtk_msgs::ImuRawMulti_<std::allocator<void> > ImuRawMulti;

typedef boost::shared_ptr< ::piksi_rtk_msgs::ImuRawMulti > ImuRawMultiPtr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::ImuRawMulti const> ImuRawMultiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'piksi_rtk_msgs': ['/home/mensonli/FusionAD/src/utility/ethz_piksi_ros/piksi_rtk_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e32f07f6279690082bb3d37f42a5fc90";
  }

  static const char* value(const ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe32f07f627969008ULL;
  static const uint64_t static_value2 = 0x2bb3d37f42a5fc90ULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/ImuRawMulti";
  }

  static const char* value(const ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Raw data from the Inertial Measurement Unit, containing accelerometer and gyroscope readings.\n\
\n\
Header header\n\
\n\
uint32 tow    # Milliseconds since start of GPS week. If the high bit is set, the time is unknown or invalid.\n\
uint8 tow_f   # Milliseconds since start of GPS week, fractional part.\n\
int16 acc_x   # Acceleration in the body frame X axis.\n\
int16 acc_y   # Acceleration in the body frame Y axis.\n\
int16 acc_z   # Acceleration in the body frame Z axis.\n\
int16 gyr_x   # Angular rate around the body frame X axis.\n\
int16 gyr_y   # Angular rate around the body frame Y axis.\n\
int16 gyr_z   # Angular rate around the body frame Z axis.\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tow);
      stream.next(m.tow_f);
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
      stream.next(m.gyr_x);
      stream.next(m.gyr_y);
      stream.next(m.gyr_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuRawMulti_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_rtk_msgs::ImuRawMulti_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tow: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tow);
    s << indent << "tow_f: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tow_f);
    s << indent << "acc_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_z);
    s << indent << "gyr_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyr_x);
    s << indent << "gyr_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyr_y);
    s << indent << "gyr_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyr_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_IMURAWMULTI_H
