// Generated by gencpp from file piksi_rtk_msgs/MagRaw.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_MAGRAW_H
#define PIKSI_RTK_MSGS_MESSAGE_MAGRAW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct MagRaw_
{
  typedef MagRaw_<ContainerAllocator> Type;

  MagRaw_()
    : header()
    , tow(0)
    , tow_f(0)
    , mag_x(0)
    , mag_y(0)
    , mag_z(0)  {
    }
  MagRaw_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tow(0)
    , tow_f(0)
    , mag_x(0)
    , mag_y(0)
    , mag_z(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _tow_type;
  _tow_type tow;

   typedef uint8_t _tow_f_type;
  _tow_f_type tow_f;

   typedef int16_t _mag_x_type;
  _mag_x_type mag_x;

   typedef int16_t _mag_y_type;
  _mag_y_type mag_y;

   typedef int16_t _mag_z_type;
  _mag_z_type mag_z;





  typedef boost::shared_ptr< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> const> ConstPtr;

}; // struct MagRaw_

typedef ::piksi_rtk_msgs::MagRaw_<std::allocator<void> > MagRaw;

typedef boost::shared_ptr< ::piksi_rtk_msgs::MagRaw > MagRawPtr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::MagRaw const> MagRawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'piksi_rtk_msgs': ['/home/mensonli/FusionAD/src/utility/ethz_piksi_ros/piksi_rtk_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79dfa3690a8019ef8383e9c5637520d8";
  }

  static const char* value(const ::piksi_rtk_msgs::MagRaw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79dfa3690a8019efULL;
  static const uint64_t static_value2 = 0x8383e9c5637520d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/MagRaw";
  }

  static const char* value(const ::piksi_rtk_msgs::MagRaw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Raw data from the Magnetometer.\n\
\n\
Header header\n\
\n\
uint32 tow    # Milliseconds since start of GPS week. If the high bit is set, the time is unknown or invalid.\n\
uint8 tow_f   # Milliseconds since start of GPS week, fractional part.\n\
int16 mag_x   # Magnetometer value in the body frame X axis.\n\
int16 mag_y   # Magnetometer value in the body frame Y axis.\n\
int16 mag_z   # Magnetometer value in the body frame Z axis.\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::piksi_rtk_msgs::MagRaw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tow);
      stream.next(m.tow_f);
      stream.next(m.mag_x);
      stream.next(m.mag_y);
      stream.next(m.mag_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagRaw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::MagRaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_rtk_msgs::MagRaw_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tow: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tow);
    s << indent << "tow_f: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tow_f);
    s << indent << "mag_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mag_x);
    s << indent << "mag_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mag_y);
    s << indent << "mag_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mag_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_MAGRAW_H
