// Generated by gencpp from file piksi_rtk_msgs/PosLlh.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_POSLLH_H
#define PIKSI_RTK_MSGS_MESSAGE_POSLLH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct PosLlh_
{
  typedef PosLlh_<ContainerAllocator> Type;

  PosLlh_()
    : header()
    , tow(0)
    , lat(0.0)
    , lon(0.0)
    , height(0.0)
    , h_accuracy(0)
    , v_accuracy(0)
    , n_sats(0)
    , flags(0)  {
    }
  PosLlh_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tow(0)
    , lat(0.0)
    , lon(0.0)
    , height(0.0)
    , h_accuracy(0)
    , v_accuracy(0)
    , n_sats(0)
    , flags(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _tow_type;
  _tow_type tow;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _height_type;
  _height_type height;

   typedef uint16_t _h_accuracy_type;
  _h_accuracy_type h_accuracy;

   typedef uint16_t _v_accuracy_type;
  _v_accuracy_type v_accuracy;

   typedef uint8_t _n_sats_type;
  _n_sats_type n_sats;

   typedef uint8_t _flags_type;
  _flags_type flags;





  typedef boost::shared_ptr< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> const> ConstPtr;

}; // struct PosLlh_

typedef ::piksi_rtk_msgs::PosLlh_<std::allocator<void> > PosLlh;

typedef boost::shared_ptr< ::piksi_rtk_msgs::PosLlh > PosLlhPtr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::PosLlh const> PosLlhConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'piksi_rtk_msgs': ['/home/mensonli/FusionAD/src/utility/ethz_piksi_ros/piksi_rtk_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d021811eaa897569f2acbd0dbd803b3";
  }

  static const char* value(const ::piksi_rtk_msgs::PosLlh_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d021811eaa89756ULL;
  static const uint64_t static_value2 = 0x9f2acbd0dbd803b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/PosLlh";
  }

  static const char* value(const ::piksi_rtk_msgs::PosLlh_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This position solution message reports the absolute geodetic coordinates and the status (single point\n\
# vs pseudo-absolute RTK) of the position solution. If the rover receiver knows the surveyed position of\n\
# the base station and has an RTK solution, this reports a pseudo-absolute position solution using the\n\
# base station position and the rover's RTK baseline vector. The full GPS time is given by the preceding\n\
# MSG GPS TIME with the matching time-of-week (tow).\n\
\n\
Header header\n\
\n\
uint32 tow          # GPS Time of Week [ms].\n\
float64 lat         # Latitude [deg].\n\
float64 lon         # Longitude [deg].\n\
float64 height      # Height [deg].\n\
uint16 h_accuracy   # Horizontal position accuracy estimate (not implemented). Defaults to 0.\n\
uint16 v_accuracy   # Vertical position accuracy estimate (not implemented). Defaults to 0.\n\
uint8 n_sats        # Number of satellites used in solution.\n\
uint8 flags         # Status flags, see MSG_POS_ECEF message description in SBP documentation.\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::piksi_rtk_msgs::PosLlh_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tow);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.height);
      stream.next(m.h_accuracy);
      stream.next(m.v_accuracy);
      stream.next(m.n_sats);
      stream.next(m.flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosLlh_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::PosLlh_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_rtk_msgs::PosLlh_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tow: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tow);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "h_accuracy: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.h_accuracy);
    s << indent << "v_accuracy: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.v_accuracy);
    s << indent << "n_sats: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.n_sats);
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_POSLLH_H
