// Generated by gencpp from file piksi_rtk_msgs/SettingsWrite.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_SETTINGSWRITE_H
#define PIKSI_RTK_MSGS_MESSAGE_SETTINGSWRITE_H

#include <ros/service_traits.h>


#include <piksi_rtk_msgs/SettingsWriteRequest.h>
#include <piksi_rtk_msgs/SettingsWriteResponse.h>


namespace piksi_rtk_msgs
{

struct SettingsWrite
{

typedef SettingsWriteRequest Request;
typedef SettingsWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SettingsWrite
} // namespace piksi_rtk_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::piksi_rtk_msgs::SettingsWrite > {
  static const char* value()
  {
    return "213f9437df3a9ccdceeabec724b32fdc";
  }

  static const char* value(const ::piksi_rtk_msgs::SettingsWrite&) { return value(); }
};

template<>
struct DataType< ::piksi_rtk_msgs::SettingsWrite > {
  static const char* value()
  {
    return "piksi_rtk_msgs/SettingsWrite";
  }

  static const char* value(const ::piksi_rtk_msgs::SettingsWrite&) { return value(); }
};


// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsWriteRequest> should match 
// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsWrite > 
template<>
struct MD5Sum< ::piksi_rtk_msgs::SettingsWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::piksi_rtk_msgs::SettingsWrite >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::piksi_rtk_msgs::SettingsWriteRequest> should match 
// service_traits::DataType< ::piksi_rtk_msgs::SettingsWrite > 
template<>
struct DataType< ::piksi_rtk_msgs::SettingsWriteRequest>
{
  static const char* value()
  {
    return DataType< ::piksi_rtk_msgs::SettingsWrite >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsWriteResponse> should match 
// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsWrite > 
template<>
struct MD5Sum< ::piksi_rtk_msgs::SettingsWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::piksi_rtk_msgs::SettingsWrite >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::piksi_rtk_msgs::SettingsWriteResponse> should match 
// service_traits::DataType< ::piksi_rtk_msgs::SettingsWrite > 
template<>
struct DataType< ::piksi_rtk_msgs::SettingsWriteResponse>
{
  static const char* value()
  {
    return DataType< ::piksi_rtk_msgs::SettingsWrite >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_SETTINGSWRITE_H
