// Generated by gencpp from file piksi_rtk_msgs/SettingsReadReq.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_SETTINGSREADREQ_H
#define PIKSI_RTK_MSGS_MESSAGE_SETTINGSREADREQ_H

#include <ros/service_traits.h>


#include <piksi_rtk_msgs/SettingsReadReqRequest.h>
#include <piksi_rtk_msgs/SettingsReadReqResponse.h>


namespace piksi_rtk_msgs
{

struct SettingsReadReq
{

typedef SettingsReadReqRequest Request;
typedef SettingsReadReqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SettingsReadReq
} // namespace piksi_rtk_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::piksi_rtk_msgs::SettingsReadReq > {
  static const char* value()
  {
    return "d894dfc3bc541068b4b4593028b123ee";
  }

  static const char* value(const ::piksi_rtk_msgs::SettingsReadReq&) { return value(); }
};

template<>
struct DataType< ::piksi_rtk_msgs::SettingsReadReq > {
  static const char* value()
  {
    return "piksi_rtk_msgs/SettingsReadReq";
  }

  static const char* value(const ::piksi_rtk_msgs::SettingsReadReq&) { return value(); }
};


// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsReadReqRequest> should match 
// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsReadReq > 
template<>
struct MD5Sum< ::piksi_rtk_msgs::SettingsReadReqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::piksi_rtk_msgs::SettingsReadReq >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsReadReqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::piksi_rtk_msgs::SettingsReadReqRequest> should match 
// service_traits::DataType< ::piksi_rtk_msgs::SettingsReadReq > 
template<>
struct DataType< ::piksi_rtk_msgs::SettingsReadReqRequest>
{
  static const char* value()
  {
    return DataType< ::piksi_rtk_msgs::SettingsReadReq >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsReadReqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsReadReqResponse> should match 
// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsReadReq > 
template<>
struct MD5Sum< ::piksi_rtk_msgs::SettingsReadReqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::piksi_rtk_msgs::SettingsReadReq >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsReadReqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::piksi_rtk_msgs::SettingsReadReqResponse> should match 
// service_traits::DataType< ::piksi_rtk_msgs::SettingsReadReq > 
template<>
struct DataType< ::piksi_rtk_msgs::SettingsReadReqResponse>
{
  static const char* value()
  {
    return DataType< ::piksi_rtk_msgs::SettingsReadReq >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsReadReqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_SETTINGSREADREQ_H
