// Generated by gencpp from file piksi_rtk_msgs/SettingsReadResp.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_SETTINGSREADRESP_H
#define PIKSI_RTK_MSGS_MESSAGE_SETTINGSREADRESP_H

#include <ros/service_traits.h>


#include <piksi_rtk_msgs/SettingsReadRespRequest.h>
#include <piksi_rtk_msgs/SettingsReadRespResponse.h>


namespace piksi_rtk_msgs
{

struct SettingsReadResp
{

typedef SettingsReadRespRequest Request;
typedef SettingsReadRespResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SettingsReadResp
} // namespace piksi_rtk_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::piksi_rtk_msgs::SettingsReadResp > {
  static const char* value()
  {
    return "c7380bc20753c3393be149ee20d6b7a4";
  }

  static const char* value(const ::piksi_rtk_msgs::SettingsReadResp&) { return value(); }
};

template<>
struct DataType< ::piksi_rtk_msgs::SettingsReadResp > {
  static const char* value()
  {
    return "piksi_rtk_msgs/SettingsReadResp";
  }

  static const char* value(const ::piksi_rtk_msgs::SettingsReadResp&) { return value(); }
};


// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsReadRespRequest> should match 
// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsReadResp > 
template<>
struct MD5Sum< ::piksi_rtk_msgs::SettingsReadRespRequest>
{
  static const char* value()
  {
    return MD5Sum< ::piksi_rtk_msgs::SettingsReadResp >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsReadRespRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::piksi_rtk_msgs::SettingsReadRespRequest> should match 
// service_traits::DataType< ::piksi_rtk_msgs::SettingsReadResp > 
template<>
struct DataType< ::piksi_rtk_msgs::SettingsReadRespRequest>
{
  static const char* value()
  {
    return DataType< ::piksi_rtk_msgs::SettingsReadResp >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsReadRespRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsReadRespResponse> should match 
// service_traits::MD5Sum< ::piksi_rtk_msgs::SettingsReadResp > 
template<>
struct MD5Sum< ::piksi_rtk_msgs::SettingsReadRespResponse>
{
  static const char* value()
  {
    return MD5Sum< ::piksi_rtk_msgs::SettingsReadResp >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsReadRespResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::piksi_rtk_msgs::SettingsReadRespResponse> should match 
// service_traits::DataType< ::piksi_rtk_msgs::SettingsReadResp > 
template<>
struct DataType< ::piksi_rtk_msgs::SettingsReadRespResponse>
{
  static const char* value()
  {
    return DataType< ::piksi_rtk_msgs::SettingsReadResp >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SettingsReadRespResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_SETTINGSREADRESP_H
