// Generated by gencpp from file piksi_rtk_msgs/UartState_V2_3_15.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_UARTSTATE_V2_3_15_H
#define PIKSI_RTK_MSGS_MESSAGE_UARTSTATE_V2_3_15_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct UartState_V2_3_15_
{
  typedef UartState_V2_3_15_<ContainerAllocator> Type;

  UartState_V2_3_15_()
    : header()
    , latency_avg(0)
    , latency_lmin(0)
    , latency_lmax(0)
    , latency_current(0)
    , obs_period_avg(0)
    , obs_period_pmin(0)
    , obs_period_pmax(0)
    , obs_period_current(0)  {
    }
  UartState_V2_3_15_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latency_avg(0)
    , latency_lmin(0)
    , latency_lmax(0)
    , latency_current(0)
    , obs_period_avg(0)
    , obs_period_pmin(0)
    , obs_period_pmax(0)
    , obs_period_current(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _latency_avg_type;
  _latency_avg_type latency_avg;

   typedef int32_t _latency_lmin_type;
  _latency_lmin_type latency_lmin;

   typedef int32_t _latency_lmax_type;
  _latency_lmax_type latency_lmax;

   typedef int32_t _latency_current_type;
  _latency_current_type latency_current;

   typedef int32_t _obs_period_avg_type;
  _obs_period_avg_type obs_period_avg;

   typedef int32_t _obs_period_pmin_type;
  _obs_period_pmin_type obs_period_pmin;

   typedef int32_t _obs_period_pmax_type;
  _obs_period_pmax_type obs_period_pmax;

   typedef int32_t _obs_period_current_type;
  _obs_period_current_type obs_period_current;





  typedef boost::shared_ptr< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> const> ConstPtr;

}; // struct UartState_V2_3_15_

typedef ::piksi_rtk_msgs::UartState_V2_3_15_<std::allocator<void> > UartState_V2_3_15;

typedef boost::shared_ptr< ::piksi_rtk_msgs::UartState_V2_3_15 > UartState_V2_3_15Ptr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::UartState_V2_3_15 const> UartState_V2_3_15ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'piksi_rtk_msgs': ['/home/mensonli/FusionAD/src/utility/ethz_piksi_ros/piksi_rtk_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eab7c26cb7da9615284c0c7450fdcec3";
  }

  static const char* value(const ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeab7c26cb7da9615ULL;
  static const uint64_t static_value2 = 0x284c0c7450fdcec3ULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/UartState_V2_3_15";
  }

  static const char* value(const ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The UART message reports data latency and throughput of the UART channels providing SBP I/O.\n\
\n\
# Message definition based on libsbp v2.3.15, only some field were selected for the original SBP message (same ones\n\
# used in piksi_tools/console/system_monitor_view.py, function \"uart_state_callback\").\n\
\n\
Header header\n\
\n\
int32 latency_avg               # Average latency [ms].\n\
int32 latency_lmin              # Minimum latency [ms].\n\
int32 latency_lmax              # Maximum latency [ms].\n\
int32 latency_current           # Smoothed estimate of the current latency [ms].\n\
int32 obs_period_avg            # Average period [ms].\n\
int32 obs_period_pmin           # Minimum period [ms].\n\
int32 obs_period_pmax           # Maximum period [ms].\n\
int32 obs_period_current        # Smoothed estimate of the current preiod [ms].\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latency_avg);
      stream.next(m.latency_lmin);
      stream.next(m.latency_lmax);
      stream.next(m.latency_current);
      stream.next(m.obs_period_avg);
      stream.next(m.obs_period_pmin);
      stream.next(m.obs_period_pmax);
      stream.next(m.obs_period_current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UartState_V2_3_15_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_rtk_msgs::UartState_V2_3_15_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latency_avg: ";
    Printer<int32_t>::stream(s, indent + "  ", v.latency_avg);
    s << indent << "latency_lmin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.latency_lmin);
    s << indent << "latency_lmax: ";
    Printer<int32_t>::stream(s, indent + "  ", v.latency_lmax);
    s << indent << "latency_current: ";
    Printer<int32_t>::stream(s, indent + "  ", v.latency_current);
    s << indent << "obs_period_avg: ";
    Printer<int32_t>::stream(s, indent + "  ", v.obs_period_avg);
    s << indent << "obs_period_pmin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.obs_period_pmin);
    s << indent << "obs_period_pmax: ";
    Printer<int32_t>::stream(s, indent + "  ", v.obs_period_pmax);
    s << indent << "obs_period_current: ";
    Printer<int32_t>::stream(s, indent + "  ", v.obs_period_current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_UARTSTATE_V2_3_15_H
