// Generated by gencpp from file velodyne_puck_msgs/VelodynePuckScan.msg
// DO NOT EDIT!


#ifndef VELODYNE_PUCK_MSGS_MESSAGE_VELODYNEPUCKSCAN_H
#define VELODYNE_PUCK_MSGS_MESSAGE_VELODYNEPUCKSCAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <velodyne_puck_msgs/VelodynePuckPoint.h>

namespace velodyne_puck_msgs
{
template <class ContainerAllocator>
struct VelodynePuckScan_
{
  typedef VelodynePuckScan_<ContainerAllocator> Type;

  VelodynePuckScan_()
    : altitude(0.0)
    , points()  {
    }
  VelodynePuckScan_(const ContainerAllocator& _alloc)
    : altitude(0.0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef double _altitude_type;
  _altitude_type altitude;

   typedef std::vector< ::velodyne_puck_msgs::VelodynePuckPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::velodyne_puck_msgs::VelodynePuckPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> const> ConstPtr;

}; // struct VelodynePuckScan_

typedef ::velodyne_puck_msgs::VelodynePuckScan_<std::allocator<void> > VelodynePuckScan;

typedef boost::shared_ptr< ::velodyne_puck_msgs::VelodynePuckScan > VelodynePuckScanPtr;
typedef boost::shared_ptr< ::velodyne_puck_msgs::VelodynePuckScan const> VelodynePuckScanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace velodyne_puck_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'velodyne_puck_msgs': ['/home/mensonli/FusionAD/src/utility/velodyne_puck/velodyne_puck_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcd29f667509c681a7820aacabe51d58";
  }

  static const char* value(const ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcd29f667509c681ULL;
  static const uint64_t static_value2 = 0xa7820aacabe51d58ULL;
};

template<class ContainerAllocator>
struct DataType< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "velodyne_puck_msgs/VelodynePuckScan";
  }

  static const char* value(const ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Altitude of all the points within this scan\n\
float64 altitude\n\
\n\
# The valid points in this scan sorted by azimuth\n\
# from 0 to 359.99\n\
VelodynePuckPoint[] points\n\
\n\
================================================================================\n\
MSG: velodyne_puck_msgs/VelodynePuckPoint\n\
# Time when the point is captured\n\
float32 time\n\
\n\
# Converted distance in the sensor frame\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
# Raw measurement from velodyne puck\n\
float64 azimuth\n\
float64 distance\n\
float64 intensity\n\
";
  }

  static const char* value(const ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.altitude);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelodynePuckScan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::velodyne_puck_msgs::VelodynePuckScan_<ContainerAllocator>& v)
  {
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::velodyne_puck_msgs::VelodynePuckPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VELODYNE_PUCK_MSGS_MESSAGE_VELODYNEPUCKSCAN_H
